class_name PixelLuffy

const PALETTE: Dictionary = {
	"K": Color(0.08, 0.08, 0.08),
	"W": Color(0.95, 0.95, 0.92),
	"S": Color(0.93, 0.77, 0.58),
	"s": Color(0.76, 0.60, 0.44),
	"A": Color(0.88, 0.15, 0.10),
	"a": Color(0.65, 0.08, 0.06),
	"B": Color(0.18, 0.18, 0.20),
	"b": Color(0.10, 0.10, 0.12),
	"H": Color(0.12, 0.10, 0.10),
	"h": Color(0.06, 0.05, 0.05),
	"Y": Color(0.86, 0.72, 0.30),
	"y": Color(0.68, 0.54, 0.18),
	"R": Color(0.90, 0.15, 0.15),
	"E": Color(0.97, 0.97, 0.97),
	"P": Color(0.14, 0.14, 0.18),
	"N": Color(0.70, 0.55, 0.40),
}

static func get_frame(state: String) -> PackedStringArray:
	match state:
		"idle0":  return IDLE0
		"idle1":  return IDLE1
		"attack": return ATTACK
		"block":  return BLOCK
		"dead":   return DEAD
	return IDLE0

# Each row MUST be exactly 20 characters.
# Layout:
#  rows 0-2  : straw hat (crown + wide brim)
#  row 3     : red ribbon under brim
#  rows 4-6  : hair under hat / forehead
#  rows 7-15 : face (eyes, X scar, nose, mouth)
#  rows 16-24: red vest open V (chest skin) + arms
#  rows 25-28: dark shorts
#  rows 29-31: bare feet
static var IDLE0 := PackedStringArray([
	"....KYYYYYYYYK......",
	"....KYYYYYYYYK......",
	".KyYYYYYYYYYYYYYYyK.",
	"....RRRRRRRRRR......",
	"...KHHHKKKKKKHHHK...",
	"...KHHKKKKKKKKHHK...",
	"...KKSSSSSSSSSSKK...",
	"...KSSSSSSSSSSSSK...",
	"...KSEEPKSSKEEPSK...",
	"...KSEEPKSSKEEPSK...",
	"...KSSSSSSRRSSSSK...",
	"...KSSSSSRSSSSSSK...",
	"...KSSSSSSNNSSSSK...",
	"...KSSSSSSSSSSSSK...",
	"...KSSSSKKKKSSSSK...",
	"...KsssssssssssK....",
	"..AAAAaSSSSSSaAAAA..",
	"..AAAaSSSSSSSSaAAA..",
	".SAAAaSSSSSSSSaAAAS.",
	".SAAAaSSSSSSSSaAAAS.",
	"..AAAaSSSSSSSSaAAA..",
	"..AAAaSSSSSSSSaAAA..",
	"..AAAAaSSSSSSaAAAA..",
	"..AAAAAAaaaaAAAAAA..",
	"..aaaaaaaaaaaaaaaa..",
	"...BBBBBBBBBBBBBB...",
	"...BBBbBBBBBBbBBB...",
	"...BBBBBBBBBBBBBB...",
	"...BBBBB....BBBBB...",
	"...SSSSS....SSSSS...",
	"..SssSSS....SssSSS..",
	"..ssssss....ssssss..",
])

static var IDLE1 := PackedStringArray([
	"....................",
	"....KYYYYYYYYK......",
	"....KYYYYYYYYK......",
	".KyYYYYYYYYYYYYYYyK.",
	"....RRRRRRRRRR......",
	"...KHHHKKKKKKHHHK...",
	"...KHHKKKKKKKKHHK...",
	"...KKSSSSSSSSSSKK...",
	"...KSSSSSSSSSSSSK...",
	"...KSEEPKSSKEEPSK...",
	"...KSEEPKSSKEEPSK...",
	"...KSSSSSSRRSSSSK...",
	"...KSSSSSRSSSSSSK...",
	"...KSSSSSSNNSSSSK...",
	"...KSSSSSSSSSSSSK...",
	"...KSSSSKKKKSSSSK...",
	"...KsssssssssssK....",
	"..AAAAaSSSSSSaAAAA..",
	"..AAAaSSSSSSSSaAAA..",
	".SAAAaSSSSSSSSaAAAS.",
	".SAAAaSSSSSSSSaAAAS.",
	"..AAAaSSSSSSSSaAAA..",
	"..AAAaSSSSSSSSaAAA..",
	"..AAAAaSSSSSSaAAAA..",
	"..AAAAAAaaaaAAAAAA..",
	"...BBBBBBBBBBBBBB...",
	"...BBBbBBBBBBbBBB...",
	"...BBBBBBBBBBBBBB...",
	"...BBBBB....BBBBB...",
	"...SSSSS....SSSSS...",
	"..SssSSS....SssSSS..",
	"..ssssss....ssssss..",
])

# Attack: Gomu Gomu Pistol — right arm stretches out across the screen.
static var ATTACK := PackedStringArray([
	"....KYYYYYYYYK......",
	"....KYYYYYYYYK......",
	".KyYYYYYYYYYYYYYYyK.",
	"....RRRRRRRRRR......",
	"...KHHHKKKKKKHHHK...",
	"...KHHKKKKKKKKHHK...",
	"...KKSSSSSSSSSSKK...",
	"...KSSSSSSSSSSSSK...",
	"...KSEEPKSSKEEPSK...",
	"...KSEEPKSSKEEPSK...",
	"...KSSSSSSRRSSSSK...",
	"...KSSSSSRSSSSSSK...",
	"...KSSSSSSNNSSSSK...",
	"...KSSSSSSSSSSSSK...",
	"...KSSSSKKKKSSSSK...",
	"...KsssssssssssK....",
	"..AAAAaSSSSSSaAAAA..",
	"..AAAaSSSSSSSSaAAAa.",
	".SAAAaSSSSSSSSSSSSSS",
	".SAAAaSSSSSSSSSSSSSS",
	"..AAAaSSSSSSSSaAAAa.",
	"..AAAaSSSSSSSSaAAA..",
	"..AAAAaSSSSSSaAAAA..",
	"..AAAAAAaaaaAAAAAA..",
	"..aaaaaaaaaaaaaaaa..",
	"...BBBBBBBBBBBBBB...",
	"...BBBbBBBBBBbBBB...",
	"...BBBBBBBBBBBBBB...",
	"...BBBBB....BBBBB...",
	"...SSSSS....SSSSS...",
	"..SssSSS....SssSSS..",
	"..ssssss....ssssss..",
])

# Block: arms up in front, slight crouch (body shifted down).
static var BLOCK := PackedStringArray([
	"....................",
	"....KYYYYYYYYK......",
	"....KYYYYYYYYK......",
	".KyYYYYYYYYYYYYYYyK.",
	"....RRRRRRRRRR......",
	"...KHHHKKKKKKHHHK...",
	"...KHHKKKKKKKKHHK...",
	"...KKSSSSSSSSSSKK...",
	"...KSSSSSSSSSSSSK...",
	"...KSEEPKSSKEEPSK...",
	"...KSEEPKSSKEEPSK...",
	"...KSSSSSSRRSSSSK...",
	"...KSSSSSRSSSSSSK...",
	"...KSSSSSSNNSSSSK...",
	"...KSSSSSSSSSSSSK...",
	"...KSSSSKKKKSSSSK...",
	"...KsssssssssssK....",
	"..SSSSAAAAAAAASSSS..",
	"..SSSSAAaaaaAASSSS..",
	"..SSSSAAAAAAAASSSS..",
	"..AAAaSSSSSSSSaAAA..",
	"..AAAaSSSSSSSSaAAA..",
	"..AAAAaSSSSSSaAAAA..",
	"..AAAAAAaaaaAAAAAA..",
	"..aaaaaaaaaaaaaaaa..",
	"...BBBBBBBBBBBBBB...",
	"...BBBbBBBBBBbBBB...",
	"...BBBBBBBBBBBBBB...",
	"...BBBBB....BBBBB...",
	"...SSSSS....SSSSS...",
	"..SssSSS....SssSSS..",
	"..ssssss....ssssss..",
])

# Dead: lying flat on the ground, straw hat tipped to the side.
static var DEAD := PackedStringArray([
	"....................",
	"....................",
	"....................",
	"....................",
	"....................",
	"....................",
	"....................",
	"....................",
	"....................",
	"....................",
	"....................",
	"....................",
	"....................",
	"....................",
	"....................",
	"....................",
	"....................",
	"....................",
	"....................",
	"....................",
	"....................",
	"....................",
	"....................",
	"....................",
	"...KYYK.............",
	"..KYYYYK............",
	".KKSSSSKAAAAAAAA....",
	".KSPKKPSAAaaaaAAA...",
	".KSKSSKSAAAAAAAAAA..",
	".KSSRRSSAAAAAAAAAAK.",
	"..KssssK.AAAAAAAKK..",
	"...KKKK....BBBBBB...",
])
