class_name PixelGoku

const PALETTE: Dictionary = {
	"K": Color(0.08, 0.08, 0.08),
	"W": Color(0.95, 0.95, 0.92),
	"S": Color(0.93, 0.78, 0.60),
	"s": Color(0.76, 0.62, 0.46),
	"A": Color(0.95, 0.50, 0.10),
	"a": Color(0.68, 0.33, 0.05),
	"B": Color(0.22, 0.40, 0.84),
	"E": Color(0.97, 0.97, 0.97),
	"P": Color(0.18, 0.18, 0.55),
	"Y": Color(1.00, 0.92, 0.18),
	"N": Color(0.70, 0.55, 0.40),
}

static func get_frame(state: String) -> PackedStringArray:
	match state:
		"idle0":  return IDLE0
		"idle1":  return IDLE1
		"attack": return ATTACK
		"block":  return BLOCK
		"dead":   return DEAD
	return IDLE0

static var IDLE0 := PackedStringArray([
	"...K.KKK..KKK.K.....",
	"..KK.KKK.KKK.KK.....",
	".KK.KKKKKKKKK.KK....",
	".KKKKKKKKKKKKKKKK...",
	"..KKKKKKKKKKKKKKK...",
	"...KKSSSSSSSSKKK....",
	"...KSSSSSSSSSSKK....",
	"...KSSSSSSSSSSKK....",
	"...KSSSSSSSSSSKK....",
	"...KSSEEPSSPEESK....",
	"...KSSEEPSSPEESK....",
	"...KSSSSSSSSSSSK....",
	"...KSSSSNNSSSSSK....",
	"...KSSSSSSSSSSSK....",
	"...KSSSsssssSSSK....",
	"...KBBWWWWWWWWBB....",
	"...AAAAAAAAAAAAAA...",
	"...AAaAAAAAAAAaAA...",
	"..SAAAAAAAAAAAAS....",
	"..SAAAAAAAAAAAAS....",
	"...AAAAAAAAAAAAA....",
	"...AAaAAAAAAAAaA....",
	"...AAAAAAAAAAAAA....",
	"...AAAAAAAAAAAAA....",
	"...BBBBBBBBBBBBBB...",
	"...BBBBBBBBBBBBBB...",
	"...AAAAAAaaAAAAAA...",
	"...AAaAAAaaAAAAaA...",
	"...KKKK......KKKK...",
	"...KKKK......KKKK...",
	"..KKKKK......KKKKK..",
	"..KKKKK......KKKKK..",
])

static var IDLE1 := PackedStringArray([
	"...K.KKK..KKK.K.....",
	"..KK.KKK.KKK.KK.....",
	".KK.KKKKKKKKK.KK....",
	".KKKKKKKKKKKKKKKK...",
	"..KKKKKKKKKKKKKKK...",
	"...KKSSSSSSSSKKK....",
	"...KSSSSSSSSSSKK....",
	"...KSSSSSSSSSSKK....",
	"...KSSSSSSSSSSKK....",
	"...KSSEEPSSPEESK....",
	"...KSSEEPSSPEESK....",
	"...KSSSSSSSSSSSK....",
	"...KSSSSNNSSSSSK....",
	"...KSSSSSSSSSSSK....",
	"...KSSSsssssSSSK....",
	"....................",
	"...KBBWWWWWWWWBB....",
	"...AAAAAAAAAAAAAA...",
	"...AAaAAAAAAAAaAA...",
	"..SAAAAAAAAAAAAS....",
	"..SAAAAAAAAAAAAS....",
	"...AAAAAAAAAAAAA....",
	"...AAaAAAAAAAAaA....",
	"...AAAAAAAAAAAAA....",
	"...BBBBBBBBBBBBBB...",
	"...BBBBBBBBBBBBBB...",
	"...AAAAAAaaAAAAAA...",
	"...AAaAAAaaAAAAaA...",
	"...KKKK......KKKK...",
	"...KKKK......KKKK...",
	"..KKKKK......KKKKK..",
	"..KKKKK......KKKKK..",
])

static var ATTACK := PackedStringArray([
	"...K.KKK..KKK.K.....",
	"..KK.KKK.KKK.KK.....",
	".KK.KKKKKKKKK.KK....",
	".KKKKKKKKKKKKKKKK...",
	"..KKKKKKKKKKKKKKK...",
	"...KKSSSSSSSSKKK....",
	"...KSSSSSSSSSSKK....",
	"...KSSSSSSSSSSKK....",
	"....KSSSSSSSSSKK....",
	"....KSSPEESSPEESK...",
	"....KSSPEESSPEESK...",
	"....KSSSSSSSSSSSK...",
	"....KSSSSNNSSSSSK...",
	"....KSSSSSSSSSSSK...",
	"....KSSSsssssSSSK...",
	"....KBBWWWWWWWWBB...",
	"....AAAAAAAAAAAAAA..",
	"....AAaAAAAAAAASSSY.",
	"...SAAAAAAAAAAASYYY.",
	"...SAAAAAAAAAAASSSY.",
	"....AAAAAAAAAAAAA...",
	"....AAaAAAAAAAAaA...",
	"....AAAAAAAAAAAAA...",
	"....AAAAAAAAAAAAA...",
	"....BBBBBBBBBBBBBB..",
	"....BBBBBBBBBBBBBB..",
	"....AAAAAAaaAAAAAA..",
	"....AAaAAAaaAAAAaA..",
	"....KKKK......KKKK..",
	"....KKKK......KKKK..",
	"...KKKKK......KKKKK.",
	"...KKKKK......KKKKK.",
])

static var BLOCK := PackedStringArray([
	"....................",
	"...K.KKK..KKK.K.....",
	"..KK.KKK.KKK.KK.....",
	".KK.KKKKKKKKK.KK....",
	".KKKKKKKKKKKKKKKK...",
	"..KKKKKKKKKKKKKKK...",
	"...KKSSSSSSSSKKK....",
	"...KSSSSSSSSSSKK....",
	"...KSSSSSSSSSSKK....",
	"...KSSSSSSSSSSKK....",
	"...KSSEEPSSPEESK....",
	"...KSSEEPSSPEESK....",
	"...KSSSSSSSSSSSK....",
	"...KSSSSNNSSSSSK....",
	"...KSSSSSSSSSSSK....",
	"...KSSSsssssSSSK....",
	"...KBBWWWWWWWWBB....",
	"...SSSAAAAAAAASSS...",
	"...SSSAAAAAAAASSS...",
	"...SSSAAAAAAAASSS...",
	"...AAAAAAAAAAAAA....",
	"...AAaAAAAAAAAaA....",
	"...AAAAAAAAAAAAA....",
	"...AAAAAAAAAAAAA....",
	"...BBBBBBBBBBBBBB...",
	"...BBBBBBBBBBBBBB...",
	"...AAAAAAaaAAAAAA...",
	"...AAaAAAaaAAAAaA...",
	"...KKKK......KKKK...",
	"...KKKK......KKKK...",
	"..KKKKK......KKKKK..",
	"..KKKKK......KKKKK..",
])

static var DEAD := PackedStringArray([
	"....................",
	"....................",
	"....................",
	"....................",
	"....................",
	"....................",
	"....................",
	"....................",
	"....................",
	"....................",
	"....................",
	"....................",
	"....................",
	"....................",
	"....................",
	"....................",
	"....................",
	"....................",
	"....................",
	"....................",
	"....................",
	"....................",
	"....................",
	"....................",
	"....................",
	"....................",
	"....................",
	"..KKKK..............",
	".KSSSSK.............",
	".KSKPKSAAAAAAAAA....",
	".KSPKPSAAAAAAAAAA...",
	"..KSSK.AAAAAAAAAKK..",
])
