class_name PixelNaruto

const PALETTE: Dictionary = {
	"K": Color(0.08, 0.08, 0.08),
	"W": Color(0.95, 0.95, 0.92),
	"S": Color(0.94, 0.80, 0.62),
	"s": Color(0.78, 0.64, 0.48),
	"A": Color(0.96, 0.55, 0.08),
	"a": Color(0.72, 0.38, 0.04),
	"B": Color(0.22, 0.36, 0.80),
	"b": Color(0.14, 0.24, 0.58),
	"H": Color(1.00, 0.88, 0.20),
	"h": Color(0.82, 0.68, 0.10),
	"E": Color(0.97, 0.97, 0.97),
	"P": Color(0.08, 0.32, 0.72),
	"R": Color(0.88, 0.15, 0.12),
	"N": Color(0.70, 0.55, 0.40),
	"G": Color(0.75, 0.78, 0.82),
	"Y": Color(1.00, 0.92, 0.18),
}

static func get_frame(state: String) -> PackedStringArray:
	match state:
		"idle0":  return IDLE0
		"idle1":  return IDLE1
		"attack": return ATTACK
		"block":  return BLOCK
		"dead":   return DEAD
	return IDLE0

static var IDLE0 := PackedStringArray([
	"....HH.HHH.HHHH.....",
	"...HHHHHHHHHHHHH....",
	"..HHHhHHHHHhHHHHH...",
	"..HHHHHHHHHHHHHHH...",
	"..BBBBBBBGGGGBBBBB..",
	"..BBBBBBGWWWGBBBBB..",
	"..HHHSSSSSSSSSHHH...",
	"...HSSSSSSSSSSSH....",
	"...HSSEEPSSPEESH....",
	"...HSSEEPSSPEESH....",
	"...HSNNSSNNSSNNH....",
	"...HSNNSSNNSSNNH....",
	"...HSNNSSNNSSNNH....",
	"...HSSSSSsssSSSH....",
	"...HSSSSSSSSSSSH....",
	"...BBBBBBRBBBBBB....",
	"...AAABBBABBBAAA....",
	"...AAABBBABBBAAA....",
	"..SAAAAAAAAAAAAS....",
	"..SAAAAAAAAAAAAS....",
	"...AAAAAAAAAAAAA....",
	"...AAaAAAAAAAAaA....",
	"...AAAAAAAAAAAAA....",
	"...AAAAAAAAAAAAA....",
	"...AAAAAAaaAAAAAA...",
	"...AAaAAAaaAAAAaA...",
	"...AAAAAAaaAAAAAA...",
	"...AAAAAAaaAAAAAA...",
	"...KKKK......KKKK...",
	"...KKKK......KKKK...",
	"..KKKKK......KKKKK..",
	"..KKKKK......KKKKK..",
])

static var IDLE1 := PackedStringArray([
	"....HH.HHH.HHHH.....",
	"...HHHHHHHHHHHHH....",
	"..HHHhHHHHHhHHHHH...",
	"..HHHHHHHHHHHHHHH...",
	"..BBBBBBBGGGGBBBBB..",
	"..BBBBBBGWWWGBBBBB..",
	"..HHHSSSSSSSSSHHH...",
	"...HSSSSSSSSSSSH....",
	"...HSSEEPSSPEESH....",
	"...HSSEEPSSPEESH....",
	"...HSNNSSNNSSNNH....",
	"...HSNNSSNNSSNNH....",
	"...HSNNSSNNSSNNH....",
	"...HSSSSSsssSSSH....",
	"...HSSSSSSSSSSSH....",
	"....................",
	"...BBBBBBRBBBBBB....",
	"...AAABBBABBBAAA....",
	"...AAABBBABBBAAA....",
	"..SAAAAAAAAAAAAS....",
	"..SAAAAAAAAAAAAS....",
	"...AAAAAAAAAAAAA....",
	"...AAaAAAAAAAAaA....",
	"...AAAAAAAAAAAAA....",
	"...AAAAAAaaAAAAAA...",
	"...AAaAAAaaAAAAaA...",
	"...AAAAAAaaAAAAAA...",
	"...AAAAAAaaAAAAAA...",
	"...KKKK......KKKK...",
	"...KKKK......KKKK...",
	"..KKKKK......KKKKK..",
	"..KKKKK......KKKKK..",
])

static var ATTACK := PackedStringArray([
	"....HH.HHH.HHHH.....",
	"...HHHHHHHHHHHHH....",
	"..HHHhHHHHHhHHHHH...",
	"..HHHHHHHHHHHHHHH...",
	"..BBBBBBBGGGGBBBBB..",
	"..BBBBBBGWWWGBBBBB..",
	"..HHHSSSSSSSSSHHH...",
	"...HSSSSSSSSSSSH....",
	"....HSPEESSPEESH....",
	"....HSPEESSPEESH....",
	"....HSNNSSNNSSNNH...",
	"....HSNNSSNNSSNNH...",
	"....HSNNSSNNSSNNH...",
	"....HSSSSSsssSSSH...",
	"....HSSSSSSSSSSSH...",
	"....BBBBBBRBBBBBB...",
	"....AAABBBABBBAAAA..",
	"....AAABBBABBBASSSYW",
	"...SAAAAAAAAAAAASYWY",
	"...SAAAAAAAAAAAASYYY",
	"....AAAAAAAAAAAAA...",
	"....AAaAAAAAAAAaA...",
	"....AAAAAAAAAAAAA...",
	"....AAAAAAAAAAAAA...",
	"....AAAAAAaaAAAAAA..",
	"....AAaAAAaaAAAAaA..",
	"....AAAAAAaaAAAAAA..",
	"....AAAAAAaaAAAAAA..",
	"....KKKK......KKKK..",
	"....KKKK......KKKK..",
	"...KKKKK......KKKKK.",
	"...KKKKK......KKKKK.",
])

static var BLOCK := PackedStringArray([
	"....................",
	"....HH.HHH.HHHH.....",
	"...HHHHHHHHHHHHH....",
	"..HHHhHHHHHhHHHHH...",
	"..HHHHHHHHHHHHHHH...",
	"..BBBBBBBGGGGBBBBB..",
	"..BBBBBBGWWWGBBBBB..",
	"..HHHSSSSSSSSSHHH...",
	"...HSSSSSSSSSSSH....",
	"...HSSEEPSSPEESH....",
	"...HSSEEPSSPEESH....",
	"...HSNNSSNNSSNNH....",
	"...HSNNSSNNSSNNH....",
	"...HSNNSSNNSSNNH....",
	"...HSSSSSsssSSSH....",
	"...HSSSSSSSSSSSH....",
	"...BBBBBBRBBBBBB....",
	"...SSSAAAAAAAASSS...",
	"...SSSAAAAAAAASSS...",
	"...SSSAAAAAAAASSS...",
	"...AAAAAAAAAAAAA....",
	"...AAaAAAAAAAAaA....",
	"...AAAAAAAAAAAAA....",
	"...AAAAAAAAAAAAA....",
	"...AAAAAAaaAAAAAA...",
	"...AAaAAAaaAAAAaA...",
	"...AAAAAAaaAAAAAA...",
	"...AAAAAAaaAAAAAA...",
	"...KKKK......KKKK...",
	"...KKKK......KKKK...",
	"..KKKKK......KKKKK..",
	"..KKKKK......KKKKK..",
])

static var DEAD := PackedStringArray([
	"....................",
	"....................",
	"....................",
	"....................",
	"....................",
	"....................",
	"....................",
	"....................",
	"....................",
	"....................",
	"....................",
	"....................",
	"....................",
	"....................",
	"....................",
	"....................",
	"....................",
	"....................",
	"....................",
	"....................",
	"....................",
	"....................",
	"....................",
	"....................",
	"....................",
	"....................",
	"....................",
	".HHHH...............",
	"HSSSSH..............",
	"HSKPKSAAAAAAAAA.....",
	"HSPKPSAAAAAAAAAA....",
	".HSSH..AAAAAAAAAKK..",
])
