class_name PixelSakura

const PALETTE: Dictionary = {
	"K": Color(0.08, 0.08, 0.08),
	"W": Color(0.96, 0.96, 0.96),
	"S": Color(0.97, 0.86, 0.74),
	"s": Color(0.82, 0.70, 0.58),
	"A": Color(0.88, 0.12, 0.22),
	"a": Color(0.65, 0.06, 0.14),
	"B": Color(0.12, 0.12, 0.14),
	"H": Color(0.96, 0.48, 0.66),
	"h": Color(0.82, 0.32, 0.52),
	"E": Color(0.97, 0.97, 0.97),
	"P": Color(0.22, 0.68, 0.28),
	"R": Color(0.90, 0.12, 0.20),
	"Y": Color(1.00, 0.90, 0.10),
	"V": Color(0.62, 0.22, 0.72),
	"N": Color(0.82, 0.65, 0.50),
	"G": Color(0.76, 0.80, 0.84),
}

static func get_frame(state: String) -> PackedStringArray:
	match state:
		"idle0":  return IDLE0
		"idle1":  return IDLE1
		"attack": return ATTACK
		"block":  return BLOCK
		"dead":   return DEAD
	return IDLE0

static var IDLE0 := PackedStringArray([
	".....HHHHHHHHHH.....",
	"....HHHHHHHHHHHH....",
	"...HHHHHHHHHHHHHH...",
	"..RRRRRRRRRRRRRRRR..",
	"..HHHSSSSSSSSSSHHH..",
	"..HHSSSSSVSSSSSSHH..",
	"..hHSSSSSSSSSSSSHh..",
	"..hHSSSSSSSSSSSSHh..",
	"..hHSSEEPSSSPEESSHh.",
	"..hHSSEPESSEPESSSHh.",
	"..hHSSSSSSSSSSSSSHh.",
	"..hHSSSSSNNSSSSSSHh.",
	"..hHSSSSSSsSSSSSSHh.",
	"..hHSSSSSsssSSSSSHh.",
	"...hHSSSSSSSSSSSHh..",
	"....hHSSSSSSSSSHh...",
	"....AAAWWWWWWAAAA...",
	"...AAAAAAAAAAAAAA...",
	"...AAAAAAAAAAAAAA...",
	"..SAAAAAAAAAAAAAAS..",
	"..SAAAAAAAAAAAAAAS..",
	"...AAAAAAAAAAAAAA...",
	"...AAaAAAAAAAAAaA...",
	"...AAAAAAAAAAAAAA...",
	"...AAAAAAAAAAAAAA...",
	"....BBBBBBBBBBBB....",
	"....BBBBBBBBBBBB....",
	"....SSSS....SSSS....",
	"....KKKK....KKKK....",
	"....KKKK....KKKK....",
	"...KKKKK....KKKKK...",
	"...KKKKK....KKKKK...",
])

static var IDLE1 := PackedStringArray([
	".....HHHHHHHHHH.....",
	"....HHHHHHHHHHHH....",
	"...HHHHHHHHHHHHHH...",
	"..RRRRRRRRRRRRRRRR..",
	"..HHHSSSSSSSSSSHHH..",
	"..HHSSSSSVSSSSSSHH..",
	"..hHSSSSSSSSSSSSHh..",
	"..hHSSSSSSSSSSSSHh..",
	"..hHSSEEPSSSPEESSHh.",
	"..hHSSEPESSEPESSSHh.",
	"..hHSSSSSSSSSSSSSHh.",
	"..hHSSSSSNNSSSSSSHh.",
	"..hHSSSSSSsSSSSSSHh.",
	"..hHSSSSSsssSSSSSHh.",
	"...hHSSSSSSSSSSSHh..",
	"....hHSSSSSSSSSHh...",
	"....................",
	"....AAAWWWWWWAAAA...",
	"...AAAAAAAAAAAAAA...",
	"..SAAAAAAAAAAAAAAS..",
	"..SAAAAAAAAAAAAAAS..",
	"...AAAAAAAAAAAAAA...",
	"...AAaAAAAAAAAAaA...",
	"...AAAAAAAAAAAAAA...",
	"...AAAAAAAAAAAAAA...",
	"....BBBBBBBBBBBB....",
	"....BBBBBBBBBBBB....",
	"....SSSS....SSSS....",
	"....KKKK....KKKK....",
	"....KKKK....KKKK....",
	"...KKKKK....KKKKK...",
	"...KKKKK....KKKKK...",
])

static var ATTACK := PackedStringArray([
	".....HHHHHHHHHH.....",
	"....HHHHHHHHHHHH....",
	"...HHHHHHHHHHHHHH...",
	"..RRRRRRRRRRRRRRRR..",
	"..HHHSSSSSSSSSSHHH..",
	"..HHSSSSSVSSSSSSHH..",
	"..hHSSSSSSSSSSSSHh..",
	"..hHSSSSSSSSSSSSHh..",
	"..hHSSEPESSSEPESSHh.",
	"..hHSSPEESSSEPSSSHh.",
	"..hHSSSSSSSSSSSSSHh.",
	"..hHSSSSSNNSSSSSSHh.",
	"..hHSSSSSSsSSSSSSHh.",
	"..hHSSSSsssSSSSSSHh.",
	"...hHSSSSSSSSSSSHh..",
	"....hHSSSSSSSSSHh...",
	"....AAAWWWWWWAAYSSY.",
	"...AAAAAAAAAAAYSSSYY",
	"...AAAAAAAAAAAYSSSYY",
	"..SAAAAAAAAAAAAYYYY.",
	"..SAAAAAAAAAAAAAAS..",
	"...AAAAAAAAAAAAAA...",
	"...AAaAAAAAAAAAaA...",
	"...AAAAAAAAAAAAAA...",
	"...AAAAAAAAAAAAAA...",
	"....BBBBBBBBBBBB....",
	"....BBBBBBBBBBBB....",
	"....SSSS....SSSS....",
	"....KKKK....KKKK....",
	"....KKKK....KKKK....",
	"...KKKKK....KKKKK...",
	"...KKKKK....KKKKK...",
])

static var BLOCK := PackedStringArray([
	"....................",
	".....HHHHHHHHHH.....",
	"....HHHHHHHHHHHH....",
	"...HHHHHHHHHHHHHH...",
	"..RRRRRRRRRRRRRRRR..",
	"..HHHSSSSSSSSSSHHH..",
	"..HHSSSSSVSSSSSSHH..",
	"..hHSSSSSSSSSSSSHh..",
	"..hHSSSSSSSSSSSSHh..",
	"..hHSSEEPSSSPEESSHh.",
	"..hHSSEPESSEPESSSHh.",
	"..hHSSSSSSSSSSSSSHh.",
	"..hHSSSSSNNSSSSSSHh.",
	"..hHSSSSSSsSSSSSSHh.",
	"..hHSSSSSsssSSSSSHh.",
	"...hHSSSSSSSSSSSHh..",
	"....AAAWWWWWWAAAA...",
	"..SSSAAAAAAAAAASSS..",
	"..SSSAAAAAAAAAASSS..",
	"..SSSAAAAAAAAAASSS..",
	"...AAAAAAAAAAAAAA...",
	"...AAaAAAAAAAAAaA...",
	"...AAAAAAAAAAAAAA...",
	"...AAAAAAAAAAAAAA...",
	"...AAAAAAAAAAAAAA...",
	"....BBBBBBBBBBBB....",
	"....BBBBBBBBBBBB....",
	"....SSSS....SSSS....",
	"....KKKK....KKKK....",
	"....KKKK....KKKK....",
	"...KKKKK....KKKKK...",
	"...KKKKK....KKKKK...",
])

static var DEAD := PackedStringArray([
	"....................",
	"....................",
	"....................",
	"....................",
	"....................",
	"....................",
	"....................",
	"....................",
	"....................",
	"....................",
	"....................",
	"....................",
	"....................",
	"....................",
	"....................",
	"....................",
	"....................",
	"....................",
	"....................",
	"....................",
	"....................",
	"....................",
	"....................",
	"....................",
	"....................",
	"....................",
	"HHH.................",
	"HHHHH...............",
	"HHSSSSH.............",
	"HSKSKSH.AAAAAAAAA...",
	"HSSKSSHAAAAAAAAAAA..",
	".HSSSH.AAAAAAAABBKK.",
])
